services:
  web-drive:
    build: .
    container_name: web-drive
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/web-drive/uploads
      - ./users.db:/web-drive/users.db
      - ./templates:/web-drive/templates
      - ./.env:/web-drive/.env
      - ./gunicorn.conf.py:/web-drive/gunicorn.conf.py