services:
  web-drive:
    build: .
    container_name: web-drive
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./users.db:/app/users.db
      - ./templates:/app/templates
      - ./.env:/app/.env
